<?php
 $helper = Mage::helper('cbanners');
 $banners = $this->getBannerCollection();
?>

<?php if ($title): ?>
    <h2><a href="/"><?php echo $title ?></a></h2>
<?php endif ?>

<?php foreach ($banners as $banner): ?>
    <?php echo $helper->groupHtmlWrap($banner, 'start'); ?>

    <?php $imageData = $this->getImageBannerData($banner); ?>
    <?php $image = "<img id='{$imageData['id']}' class='{$imageData['class']}' src='/media/ibanners/{$banner->getImage()}' alt='{$banner->getAltText()}' data-secondsLeft='{$helper->getTimeLeft($banner)}' >"; ?>

    <?php if( $helper->isWithinTheTime($banner) && $banner->getIsEnabled() ): ?>


        <?php if ( $helper->haveLink() ) : ?>

            <a href="<?php echo $banner->getUrl(); ?>" target="<?php echo $banner->getUrlTarget(); ?>">

            <?php  if (trim($banner->getHtml()) != ''  ) : ?>

                <?php echo str_replace('{{image}}', $image, $banner->getHtml()); ?>

             <?php else: ?>

                <?php echo $image; ?>

            <?php  endif;?>

            </a>

        <?php else:  ?>

            <?php echo $image; ?>

        <?php endif; ?>

        <?php if($banner->getType() == 'timer'): ?>

            <script type="text/javascript">
                jQuery(function () {
                    jQuery('#timer-<?php echo $banner->getId();  ?>').countdown();
                });
            </script>

        <?php endif; ?>

    <?php endif; ?>

    <?php echo $helper->groupHtmlWrap($banner, 'end'); ?>
<?php endforeach; ?>
