<?php
 $helper = Mage::helper('cbanners');
 $banners = $this->getBannerCollection();
?>

<?php if ($title): ?>
    <h2><a href="/"><?php echo $title ?></a></h2>
<?php endif ?>


<?php foreach ($banners as $banner): ?>
    <?php echo $helper->groupHtmlWrap($banner, 'start'); ?>

        <?php if( $helper->isWithinTheTime($banner) ): ?>

            <?php if ( $helper->haveLink() ) : ?>

                <a href="<?php echo $banner->getUrl(); ?>" target="<?php echo $banner->getUrlTarget(); ?>">
                    <?php echo $this->getBannerHtml($banner); ?>
                </a>

            <?php else:  ?>

                <?php echo $this->getBannerHtml($banner); ?>

            <?php endif; ?>

            <?php if($banner->getType() == 'timer'): ?>

                <script type="text/javascript">
                    jQuery(function () {
                        jQuery('#timer-<?php echo $banner->getId();  ?>').countdown();
                    });
                </script>

            <?php endif; ?>

        <?php endif; ?>

    <?php echo $helper->groupHtmlWrap($banner, 'end'); ?>
<?php endforeach; ?>
